"""

Applies the trained model to an analyst-submitted list of individuals,
assigns a risk score to each, classifies them into priority tiers, and
generates a plain-English explanation of why each person was scored as they were.


"""

import logging
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline

from config import PRIORITY_CONFIG, FEATURE_CONFIG

logger = logging.getLogger(__name__)


def score_individuals(
    pipeline: Pipeline,
    df_input: pd.DataFrame,
    feature_columns: list,
) -> pd.DataFrame:
    """
    Runs the trained pipeline on the input DataFrame and attaches a
    risk_score column containing each person's estimated probability of
    being a suspect (a value between 0.0 and 1.0).

    Args:
        pipeline        (Pipeline):     Fitted sklearn Pipeline.
        df_input        (pd.DataFrame): Analyst input, one row per individual.
        feature_columns (list):         Feature columns the model expects.

    Returns:
        pd.DataFrame: Input DataFrame + 'risk_score' column, sorted high → low.

    """
    missing = [c for c in feature_columns if c not in df_input.columns]
    if missing:
        raise ValueError(
            f"The input file is missing columns required by the trained model: {missing}\n"
            f"Ensure the input file was prepared using the template generated by "
            f"create_sample_template.py, or manually add these columns."
        )

    X = df_input[feature_columns].copy()
    probabilities = pipeline.predict_proba(X)[:, 1]   # P(class = 1) = risk score

    df_result = df_input.copy()
    df_result["risk_score"] = np.round(probabilities, 4)
    df_result = df_result.sort_values("risk_score", ascending=False).reset_index(drop=True)

    logger.info(
        f"Scored {len(df_result):,} individuals. "
        f"Score range: {df_result['risk_score'].min():.3f} – "
        f"{df_result['risk_score'].max():.3f}. "
        f"Mean: {df_result['risk_score'].mean():.3f}."
    )
    return df_result


def assign_priority_tiers(df_scored: pd.DataFrame) -> pd.DataFrame:
    """

    Args:
        df_scored (pd.DataFrame): DataFrame with a 'risk_score' column.

    Returns:
        pd.DataFrame: Same DataFrame with an additional 'priority_tier' column.
    """
    high_thresh   = PRIORITY_CONFIG["HIGH"]
    medium_thresh = PRIORITY_CONFIG["MEDIUM"]

    def _assign_tier(score: float) -> str:
        if score >= high_thresh:
            return "HIGH"
        elif score >= medium_thresh:
            return "MEDIUM"
        else:
            return "LOW"

    df_result = df_scored.copy()
    df_result["priority_tier"] = df_result["risk_score"].apply(_assign_tier)

    tier_counts = df_result["priority_tier"].value_counts().to_dict()
    logger.info(f"Priority breakdown — {tier_counts}")

    return df_result


def generate_explanations(
    pipeline: Pipeline,
    df_scored: pd.DataFrame,
    feature_columns: list,
    training_stats: dict = None,
    top_n_factors: int = 3,
) -> pd.DataFrame:
    """
    Generates a plain-English explanation for each individual's risk score.

    Args:
        pipeline        (Pipeline):     Fitted sklearn Pipeline.
        df_scored       (pd.DataFrame): Scored + tiered DataFrame.
        feature_columns (list):         Feature column names.
        training_stats  (dict):         Per-feature mean/std from training data.
                                        If None, deviations are not computed.
        top_n_factors   (int):          Number of top contributing factors to cite (default 3).

    Returns:
        pd.DataFrame: df_scored with an additional 'explanation' column.
    """
    rf_model    = pipeline.named_steps["classifier"]
    importances = rf_model.feature_importances_

    # Get post-encoding feature names (one-hot encoding expands categorical cols)
    try:
        encoded_feature_names = pipeline.named_steps["preprocessor"].get_feature_names_out()
    except AttributeError:
        encoded_feature_names = [f"feature_{i}" for i in range(len(importances))]

    # Map original column name → max importance across any of its encoded sub-features
    orig_to_importance = {}
    for orig_col in feature_columns:
        matching = [
            importances[i]
            for i, name in enumerate(encoded_feature_names)
            if orig_col in name
        ]
        orig_to_importance[orig_col] = max(matching) if matching else 0.0

    explanations = []

    for _, row in df_scored.iterrows():
        score = row["risk_score"]
        tier  = row["priority_tier"]

        if tier == "LOW":
            explanations.append(
                f"Risk score {score:.2f} — LOW priority. "
                f"No significant behavioral indicators were elevated."
            )
            continue

        # Build a ranked list of contributing factors for this individual
        factors = []
        for col in feature_columns:
            val = row.get(col)
            if val is None or (isinstance(val, float) and np.isnan(val)):
                continue

            importance = orig_to_importance.get(col, 0.0)

            # Compute deviation from population mean if training stats are available
            deviation_score = 0.0
            deviation_note  = ""
            if training_stats and col in training_stats:
                stats  = training_stats[col]
                mean   = stats["mean"]
                std    = stats["std"]
                if std > 0:
                    z = (float(val) - mean) / std
                    deviation_score = abs(z)
                    if z >= 2.0:
                        deviation_note = f"strongly elevated (pop. avg ≈ {mean:.2f})"
                    elif z >= 1.0:
                        deviation_note = f"above average (pop. avg ≈ {mean:.2f})"
                    elif z <= -2.0:
                        deviation_note = f"strongly below average (pop. avg ≈ {mean:.2f})"
                    elif z <= -1.0:
                        deviation_note = f"below average (pop. avg ≈ {mean:.2f})"

            combined_weight = importance * (1 + deviation_score)

            factors.append({
                "feature":        col,
                "value":          val,
                "importance":     importance,
                "deviation_note": deviation_note,
                "weight":         combined_weight,
            })

        factors.sort(key=lambda f: f["weight"], reverse=True)
        top_factors = factors[:top_n_factors]

        if not top_factors:
            explanations.append(
                f"Risk score {score:.2f} — {tier} priority. "
                f"Score elevated but insufficient feature data for breakdown."
            )
            continue

        # Format the explanation string
        parts = []
        for f in top_factors:
            part = f"{f['feature']} = {f['value']}"
            if f["deviation_note"]:
                part += f" [{f['deviation_note']}]"
            parts.append(part)

        explanation = (
            f"Risk score {score:.2f} — {tier} priority. "
            f"Key indicators: {'; '.join(parts)}."
        )
        explanations.append(explanation)

    df_result = df_scored.copy()
    df_result["explanation"] = explanations
    return df_result


def _shap_explanations(pipeline: Pipeline, X: pd.DataFrame) -> list:
    """
   
    Args:
        pipeline (Pipeline): Fitted sklearn Pipeline.
        X        (pd.DataFrame): Feature DataFrame (not yet preprocessed).

    Returns:
        list: SHAP value arrays, one per row in X.
    """
    raise NotImplementedError(
        "SHAP-based explanations are not yet enabled. "
        "Install shap (pip install shap) and implement this function "
        "following the example in the docstring."
    )



def run_prediction_pipeline(
    input_filepath: str,
    output_filepath: str,
    output_format: str = "excel",
) -> pd.DataFrame:
    """
    Full prediction flow: load model → load input → score → tier → explain → report.

    This is the entry point called by main.py's 'predict' subcommand.

    Args:
        input_filepath  (str): Path to the analyst input file (.xlsx, .csv, or .pdf).
        output_filepath (str): Path where the output report will be written.
        output_format   (str): "excel" (default) or "pdf".

    Returns:
        pd.DataFrame: Final scored, tiered, and explained DataFrame.
    """
    from data_loader import load_input_file, validate_dataframe
    from model_trainer import load_artifacts
    from report_generator import generate_excel_report, generate_pdf_summary

    # --- 1. Load model + metadata ---
    pipeline, metadata = load_artifacts()
    feature_columns    = metadata.get("feature_columns", FEATURE_CONFIG["FEATURE_COLUMNS"])
    training_stats     = metadata.get("training_stats", None)

    if not feature_columns:
        raise ValueError(
            "The loaded model has no feature columns in its metadata. "
            "Retrain the model after defining FEATURE_COLUMNS in config.py."
        )

    # --- 2. Load analyst input ---
    df_input = load_input_file(input_filepath)
    validate_dataframe(df_input, feature_columns, context="analyst input file")

    # --- 3. Score ---
    df_scored = score_individuals(pipeline, df_input, feature_columns)

    # --- 4. Assign priority tiers ---
    df_tiered = assign_priority_tiers(df_scored)

    # --- 5. Generate explanations ---
    df_explained = generate_explanations(
        pipeline, df_tiered, feature_columns, training_stats
    )

    # --- 6. Write output report ---
    if output_format == "pdf":
        generate_pdf_summary(df_explained, output_filepath)
    else:
        generate_excel_report(df_explained, output_filepath)

    return df_explained
